name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - bson
  - lz4
  - lzo
  - pytest
  - pandas
  - dask
  - pytest-cov
  - thrift
  - numpy
  - cramjam
  - pyspark
  - packaging
